2024-11-10 13:32:24,314 - INFO - [ALERT] Potential SYN flood detected from 192.168.1.3 to 20.190.146.35
2024-11-10 13:32:28,376 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%20192.168.1.3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC1F3380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:32,436 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%2020.190.146.35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC22B750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:36,520 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%20192.168.1.3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC22B390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:40,588 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%20192.168.1.3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC27CB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:44,638 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%2020.190.146.35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC27C2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:48,706 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%2020.190.146.35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC23F1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:52,797 - ERROR - Error sending alert to dashboard: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /add_alert/Possible%20Attack%20detected%20from%20IP%2020.190.146.35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9EC262580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-10 13:32:54,868 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.3:5000
2024-11-10 13:32:54,868 - INFO - [33mPress CTRL+C to quit[0m
2024-11-10 13:33:33,631 - INFO - 192.168.1.3 - - [10/Nov/2024 13:33:33] "GET / HTTP/1.1" 200 -
2024-11-10 13:33:33,849 - INFO - 192.168.1.3 - - [10/Nov/2024 13:33:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
